apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-kubelet-fix
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-kubelet-fix
  template:
    metadata:
      labels:
        app: test-kubelet-fix
    spec:
      containers:
      - name: app
        image: nginx:1.21
