apiVersion: apps/v1
kind: Deployment
metadata:
  name: pending-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pending-app
  template:
    metadata:
      labels:
        app: pending-app
    spec:
      nodeSelector:
        node-type: compute
      containers:
      - name: app
        image: nginx:1.21
